=== kdavid16/GEB15IWebXML/GEB15I_XMLTask/GEB15I_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="GEB15IXML">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Uzlet" type="UzletType" maxOccurs="unbounded"/>
                <xs:element name="Raktar" type="RaktarType" maxOccurs="unbounded"/>
                <xs:element name="Cipok" type="CipokType" maxOccurs="unbounded"/>
                <xs:element name="vasarlo" type="VasarloType" maxOccurs="unbounded"/>
                <xs:element name="rendeles" type="RendelesType" maxOccurs="unbounded"/>
                <xs:element name="Kiszallitas" type="KiszallitasType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="UzletKey">
            <xs:selector xpath="Uzlet"/>
            <xs:field xpath="@ukod"/>
        </xs:key>

        <xs:key name="CipoKey">
            <xs:selector xpath="Cipok"/>
            <xs:field xpath="@ckod"/>
        </xs:key>

        <xs:key name="RaktarKey">
            <xs:selector xpath="Raktar"/>
            <xs:field xpath="@rkod"/>
        </xs:key>

        <xs:key name="VasarloKey">
            <xs:selector xpath="vasarlo"/>
            <xs:field xpath="@vkod"/>
        </xs:key>

        <xs:key name="RendelesKey">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@rendeleskod"/>
        </xs:key>

        <xs:key name="KiszallitasKey">
            <xs:selector xpath="Kiszallitas"/>
            <xs:field xpath="@kkod"/>
        </xs:key>

        <xs:keyref name="RaktarToUzletRef" refer="UzletKey">
            <xs:selector xpath="Raktar"/>
            <xs:field xpath="@ukod"/>
        </xs:keyref>
        <xs:keyref name="CipoToUzletRef" refer="UzletKey">
            <xs:selector xpath="Cipok"/>
            <xs:field xpath="@ukod"/>
        </xs:keyref>
        <xs:keyref name="VasarloToUzletRef" refer="UzletKey">
            <xs:selector xpath="vasarlo"/>
            <xs:field xpath="@ukod"/>
        </xs:keyref>
        <xs:keyref name="RendelesToUzletRef" refer="UzletKey">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@ukod"/>
        </xs:keyref>
        <xs:keyref name="KiszallitasToUzletRef" refer="UzletKey">
            <xs:selector xpath="Kiszallitas"/>
            <xs:field xpath="@ukod"/>
        </xs:keyref>

        <xs:keyref name="RendelesToCipoRef" refer="CipoKey">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="cipo"/>
        </xs:keyref>

        <xs:keyref name="RendelesToVasarloRef" refer="VasarloKey">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@vkod"/>
        </xs:keyref>

    </xs:element>


    <xs:complexType name="UzletType">
        <xs:sequence>
            <xs:element name="elerhetoseg">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="emailcim" type="xs:string"/>
                        <xs:element name="telefon" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="nyitvatartas">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="tol" type="xs:string"/>
                        <xs:element name="ig" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cim" type="CimType"/>
            <xs:element name="nev" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ukod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="RaktarType">
        <xs:sequence>
            <xs:element name="kapacitas" type="xs:integer"/>
            <xs:element name="muszak" type="xs:string"/>
            <xs:element name="vezeto" type="xs:string"/>
            <xs:element name="hely" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="rkod" type="xs:string" use="required"/>
        <xs:attribute name="ukod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="CipokType">
        <xs:sequence>
            <xs:element name="Keszlet" type="xs:integer"/>
            <xs:element name="Marka" type="xs:string"/>
            <xs:element name="modell" type="xs:string"/>
            <xs:element name="ar" type="xs:integer"/>
            <xs:element name="Meret" type="xs:integer"/>
            <xs:element name="Szin" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ckod" type="xs:string" use="required"/>
        <xs:attribute name="ukod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="VasarloType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="CimType"/>
            <xs:element name="eletkor" type="xs:integer"/>
            <xs:element name="fizetesi_mod">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="online">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="applepay" type="xs:string"/>
                                    <xs:element name="googlepay" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="vkod" type="xs:string" use="required"/>
        <xs:attribute name="ukod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="RendelesType">
        <xs:sequence>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="osszeg" type="xs:integer"/>
            <xs:element name="cipo" type="xs:string"/>
            <xs:element name="mennyiseg" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="rendeleskod" type="xs:string" use="required"/>
        <xs:attribute name="ukod" type="xs:string" use="required"/>
        <xs:attribute name="vkod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="KiszallitasType">
        <xs:sequence>
            <xs:element name="Kamion">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="modell" type="xs:string"/>
                        <xs:element name="rendszam" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Sofor" type="xs:string"/>
            <xs:element name="Telefonszam" type="xs:string"/>
            <xs:element name="Cim" type="CimType"/>
        </xs:sequence>
        <xs:attribute name="kkod" type="xs:string" use="required"/>
        <xs:attribute name="ukod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="CimType">
        <xs:sequence>
            <xs:element name="orszag" type="xs:string" minOccurs="0"/>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== kdavid16/GEB15IWebXML/GEB15I_XMLTask/GEB15IXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<GEB15IXML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GEB15I_XMLSchema.xsd">

    <Uzlet ukod="U001">
        <elerhetoseg>
            <emailcim>info@cipobolt.hu</emailcim>
            <telefon>+36301234567</telefon>
        </elerhetoseg>
        <nyitvatartas>
            <tol>08:00</tol>
            <ig>20:00</ig>
        </nyitvatartas>
        <cim>
            <varos>Budapest</varos>
            <utca>Fő utca</utca>
            <hazszam>10</hazszam>
        </cim>
        <nev>KunKicks</nev>
    </Uzlet>

    <Raktar rkod="R001" ukod="U001">
        <kapacitas>5000</kapacitas>
        <muszak>Délelőtt</muszak>
        <vezeto>Kovács János</vezeto>
        <hely>3000</hely>
    </Raktar>
    <Raktar rkod="R002" ukod="U001">
        <kapacitas>5000</kapacitas>
        <muszak>Délután</muszak>
        <vezeto>Kovács János</vezeto>
        <hely>3000</hely>
    </Raktar>

    <Cipok ckod="C999" ukod="U001">
        <Keszlet>50</Keszlet>
        <Marka>Nike</Marka>
        <modell>Air Max</modell>
        <ar>35000</ar>
        <Meret>42</Meret>
        <Szin>Fekete</Szin>
    </Cipok>
    <Cipok ckod="C998" ukod="U001">
        <Keszlet>50</Keszlet>
        <Marka>Nike</Marka>
        <modell>Air Force</modell>
        <ar>45000</ar>
        <Meret>42</Meret>
        <Szin>Fehér</Szin>
    </Cipok>
    <Cipok ckod="C997" ukod="U001">
        <Keszlet>40</Keszlet>
        <Marka>Nike</Marka>
        <modell>Jordan 1</modell>
        <ar>55000</ar>
        <Meret>43</Meret>
        <Szin>Piros</Szin>
    </Cipok>
    <Cipok ckod="C996" ukod="U001">
        <Keszlet>30</Keszlet>
        <Marka>Nike</Marka>
        <modell>Jordan 4</modell>
        <ar>95000</ar>
        <Meret>41</Meret>
        <Szin>Sárga</Szin>
    </Cipok>
    <Cipok ckod="C995" ukod="U001">
        <Keszlet>15</Keszlet>
        <Marka>Nike</Marka>
        <modell>Jordan 4</modell>
        <ar>105000</ar>
        <Meret>40</Meret>
        <Szin>Fehér</Szin>
    </Cipok>

    <vasarlo vkod="V555" ukod="U001">
        <nev>Tóth Péter</nev>
        <cim>
            <varos>Debrecen</varos>
            <utca>Kossuth utca</utca>
            <hazszam>5</hazszam>
        </cim>
        <eletkor>30</eletkor>
        <fizetesi_mod>
            <online>
                <applepay>true</applepay>
                <googlepay>false</googlepay>
            </online>
        </fizetesi_mod>
    </vasarlo>
    <vasarlo vkod="V556" ukod="U001">
        <nev>Faragó René</nev>
        <cim>
            <varos>Muhi</varos>
            <utca>Fő utca</utca>
            <hazszam>3</hazszam>
        </cim>
        <eletkor>25</eletkor>
        <fizetesi_mod>
            <online>
                <applepay>false</applepay>
                <googlepay>false</googlepay>
            </online>
        </fizetesi_mod>
    </vasarlo>

    <rendeles rendeleskod="ORD777" ukod="U001" vkod="V555">
        <datum>2023-11-20</datum>
        <osszeg>35000</osszeg>
        <cipo>C999</cipo>
        <mennyiseg>1</mennyiseg>
    </rendeles>
    <rendeles rendeleskod="ORD888" ukod="U001" vkod="V555">
        <datum>2023-11-21</datum>
        <osszeg>90000</osszeg>
        <cipo>C998</cipo>
        <mennyiseg>2</mennyiseg>
    </rendeles>

    <Kiszallitas kkod="K888" ukod="U001">
        <Kamion>
            <modell>Mercedes Sprinter</modell>
            <rendszam>ABC-123</rendszam>
        </Kamion>
        <Sofor>Kiss Béla</Sofor>
        <Telefonszam>+36209999999</Telefonszam>
        <Cim>
            <orszag>Magyarország</orszag>
            <varos>Muhi</varos>
            <utca>Fő utca</utca>
            <hazszam>3</hazszam>
        </Cim>
    </Kiszallitas>
    <Kiszallitas kkod="K777" ukod="U001">
        <Kamion>
            <modell>Mercedes Sprinter</modell>
            <rendszam>ABC-321</rendszam>
        </Kamion>
        <Sofor>Kiss József</Sofor>
        <Telefonszam>+36309999999</Telefonszam>
        <Cim>
            <orszag>Magyarország</orszag>
            <varos>Debrecen</varos>
            <utca>Kossuth utca</utca>
            <hazszam>5</hazszam>
        </Cim>
    </Kiszallitas>

</GEB15IXML>
