<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE mozi SYSTEM "GEB15I_mozi.dtd">


<!DOCTYPE mozi [
    <!ELEMENT mozi (film*)>
    <!ELEMENT film (rendezo, szinesz, iro+)>
    <!ATTLIST film id ID #REQUIRED>
    <!ATTLIST film mufaj (horror | romanitkus | thriller) "horror">

    <!ELEMENT rendezo EMPTY>
    <!ATTLIST rendezo id ID #REQUIRED>
    <!ATTLIST rendezo nev CDATA #REQUIRED>

    <!ELEMENT szinesz EMPTY>
    <!ATTLIST szinesz id ID #REQUIRED>
    <!ATTLIST szinesz nev CDATA #REQUIRED>

    <!ELEMENT iro EMPTY>
    <!ATTLIST iro id ID #REQUIRED>
]>

<mozi>
    <film id="txn_nxm_2jb" mufaj="horror">
        <rendezo id="nzk_4xm_2jb" nev="alex"></rendezo>
        <szinesz id="u5q_4xm_2jb" nev="Madison_Ivy"></szinesz>
        <szinesz id="a">
            <gyerekszinesz />
            <musicalszinesz />
            <szinkronszinesz />
        </szinesz>
        <iro id="trv_4xm_2jb"/>
    </film>
</mozi>